name: metrics

on: 
  schedule:
    - cron: 0 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Send metrics
      env:
        API_KEY: ${{ secrets.API_KEY }}
        URL: ${{ secrets.URL }}
        STRATEGY: ${{ secrets.STRATEGY }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        AUTH_FILE: ${{ secrets.AUTH_FILE }}
      run: |
        # run example.py 
        python example.py
